import { ContainerModule } from "inversify";
import { TYPES } from "../types.di";
import { ILogger } from "@application/interfaces/ILogger";
import { WinstonSentryLogger } from "@infrastructure/services/WinstonSentryLogger";
import { IEmailService } from "@application/interfaces/IEmailService";
import { NodemailerEmailService } from "@infrastructure/services/NodemailerEmailService";
import { ITokenService } from "@application/interfaces/ITokenService";
import { JwtTokenService } from "@infrastructure/services/JwtTokenService";
import { IEncryptionService } from "@application/interfaces/IEncryptionService";
import { BcryptPasswordHasher } from "@infrastructure/services/BcryptPasswordHasher";
import { IOtpGenerator } from "@application/interfaces/IOtpGenerator";
import { OtpGenerator } from "@infrastructure/services/OtpGenerator";
import { IS3Service } from "@application/interfaces/IS3Service";
import { S3StorageService } from "@infrastructure/services/S3StorageService";
import { IEmailOtpStore } from "@application/interfaces/IEmailOtpStore";
import { UpstashEmailOtpStore } from "@infrastructure/services/UpstashEmailOtpStore";
import { IPasswordResetOtpStore } from "@application/interfaces/IPasswordResetOtpStore";
import { UpstashPasswordResetOtpStore } from "@infrastructure/services/UpstashPasswordResetOtpStore";
import { IGoogleOAuthService } from "@application/interfaces/IGoogleOAuthService";
import { GoogleOAuthService } from "@infrastructure/services/GoogleOAuthService";
import { IRefreshSessionStore } from "@application/interfaces/IRefreshSessionStore";
import { RedisRefreshSessionStore } from "@infrastructure/services/RedisRefreshSessionStore";
import { IMetalRatesApiService } from "@application/interfaces/IMetalRatesApiService";
import { MetalRatesApiService } from "@infrastructure/services/MetalRatesApiService";
import { RateScheduler } from "@infrastructure/cron/RateScheduler";

export const servicesContainer = new ContainerModule((options) => {
  options.bind<ILogger>(TYPES.ILogger).to(WinstonSentryLogger).inSingletonScope();
  options.bind<IEmailService>(TYPES.IEmailService).to(NodemailerEmailService).inSingletonScope();
  options.bind<ITokenService>(TYPES.ITokenService).to(JwtTokenService).inSingletonScope();
  options.bind<IEncryptionService>(TYPES.IEncryptionService).to(BcryptPasswordHasher).inSingletonScope();
  options.bind<IOtpGenerator>(TYPES.IOtpGenerator).to(OtpGenerator).inSingletonScope();
  options.bind<IS3Service>(TYPES.IS3Service).to(S3StorageService).inSingletonScope();
  options.bind<IEmailOtpStore>(TYPES.IEmailOtpStore).to(UpstashEmailOtpStore).inSingletonScope();
  options.bind<IPasswordResetOtpStore>(TYPES.IPasswordResetOtpStore).to(UpstashPasswordResetOtpStore).inSingletonScope();
  options.bind<IGoogleOAuthService>(TYPES.IGoogleOAuthService).to(GoogleOAuthService).inSingletonScope();
  options.bind<IRefreshSessionStore>(TYPES.IRefreshSessionStore).to(RedisRefreshSessionStore).inSingletonScope();
  options.bind<IMetalRatesApiService>(TYPES.IMetalRatesApiService).to(MetalRatesApiService).inSingletonScope();
  options.bind<RateScheduler>(TYPES.RateScheduler).to(RateScheduler).inSingletonScope();
});
