export const ROUTES = {
  AUTH: {
    REGISTER: "/register",
    LOGIN: "/login",
    LOGOUT: "/logout",
    VERIFY_EMAIL: "/verify-email",
    RESEND_VERIFICATION: "/resend-email-verification",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    REFRESH_TOKEN: "/refresh-token",
    CHANGE_PASSWORD: "/change-password",
    ME: "/me",
    GOOGLE: "/google",
    GOOGLE_CALLBACK: "/google/callback",
  },
  ADMIN: {
    BASE: "/admin",
    LIST_USERS: "/users",
    USER_DETAILS: "/users/:userId",
    USER_STATUS: "/users/:userId/status",
    USER_ROLE: "/users/:userId/role",
    UPDATE_GLOBAL_RATE: "/rates/today",
    RATE_HISTORY: "/rates/history",
    SYNC_RATES: "/rates/fetch",
  },
  SHOP: {
    BASE: "/shop",
    SAVE_ONBOARDING: "/onboarding",
    ONBOARDING_STATE: "/onboarding",
    PROFILE: "/profile",
    PHOTO_URL: "/profile/photo/upload-url",
    PHOTO: "/profile/photo",
    TODAY_RATE: "/rates/today",
    RATE_OVERRIDE: "/rates/override",
  },
};
